# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  azure-cli: circleci/azure-cli@1.2.2
  azure-acr: circleci/azure-acr@0.2.0

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.17.5

jobs:
  build:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: create npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run:
          name: create npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build
      - run: docker build -t zer0cptcontainers/data-store-api . --build-arg NPM_TOKEN=${NPM_TOKEN}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  buildDocker:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - attach_workspace:
          at: ~/repo
      - azure-acr/build-and-push-image:
          login-server-name: zer0cptcontainers.azurecr.io
          registry-name: zer0cptcontainers
          repo: data-store-api
          attach-workspace: false
          tag: ${CIRCLE_TAG/v/''}
          extra-build-args: --build-arg NPM_TOKEN=${NPM_TOKEN}

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  test-and-publish-docker:
    jobs:
      - test:
          filters:
            &filters-production # this yaml anchor is setting these values to "filters-production"
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - buildDocker:
          requires:
            - test
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
